python -m attack_resilience_complex_networks.symbolic_regression \
    --sr_data_filename ./sr_data_sf.csv \
    --loss Sigmoid \
    --target logit \
    --nosingle_step \
    --primitives d \
    --primitives s \
    --primitives w_d \
    --primitives w_s \
    --binary_operators '+' \
    --binary_operators '*'
